import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { rockHandler, paperHandler, scissorsHandler } from "@/lib/page-logic-index";

/**
 * The primary React module used to display the page and logic to the user.
 *
 * @returns The HTML page displayed to the user.
 */
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>A Very Mediocre Rock Paper Scissors</h1>

      <h2 id="header">Select an option...</h2>

      <br />

      <button className={styles.button} id="rock" onClick={rockHandler}>
        <Image
          priority
          src="/images/rock_cropped.png"
          width={144}
          height={144}
          alt="rock"
        />
      </button>
      <button className={styles.button} id="paper" onClick={paperHandler}>
        <Image
          priority
          src="/images/paper_cropped.png"
          width={144}
          height={144}
          alt="paper"
        />
      </button>
      <button className={styles.button} id="scissors" onClick={scissorsHandler}>
        <Image
          priority
          src="/images/scissors_cropped.png"
          width={144}
          height={144}
          alt="scissors"
        />
      </button>

      <h2>Opponent Choice...</h2>

      <h3 className={styles.aiMoveDisplay}><em id="aiMoveDisplay"></em></h3>

      <h1 id="roundResult"></h1>

      <footer className={styles.scoreboard}>
        <p id="wins">Wins: 0</p>
        <p id="losses">Losses: 0</p>
        <p id="ties">Ties: 0</p>
        <p id="rounds">Rounds: 0</p>
      </footer>
    </div>
  );
}
