import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

/**
 * The primary React module used to display the page and logic to the user.
 *
 * @returns The HTML page displayed to the user.
 */
export default function Home() {
  let aiChoice = -1;    // The move that the ai makes. Rock = 0, Paper = 1, Scissors = 2.
  let numOfRounds = 0;
  let numOfWins = 0;
  let numOfLosses = 0;
  let numOfTies = 0;

  /**
   * This function handles all of the logic performed when the rock button is clicked.
   */
  function rockHandler() {
    gameLogic(0);
  }

  /**
   * This function handles all of the logic performed when the paper button is clicked.
   */
  function paperHandler() {
    gameLogic(1);
  }

  /**
   * This function handles all of the logic performed when the paper button is clicked.
   */
  function scissorsHandler() {
    gameLogic(2);
  }

  /**
   * This function handles all of the rock paper scissors game logic.
   *
   * @param {number} playerChoice The move that the player makes.
   *                              0 = Rock
   *                              1 = Paper
   *                              2 = Scissors
   */
  function gameLogic(playerChoice) {
    // Initialize vars.
    loadAi();
    let wins = document.getElementById("wins");
    let losses = document.getElementById("losses");
    let ties = document.getElementById("ties");

    // Primary rock paper scissors logic.
    if (playerChoice == aiChoice) {
      incTiesElement(ties);
    } else if (playerChoice == 0 && aiChoice == 1) {
      incLossesElement(losses);
    } else if (playerChoice == 1 && aiChoice == 2) {
      incLossesElement(losses);
    } else if (playerChoice == 2 && aiChoice == 0) {
      incLossesElement(losses);
    } else if (playerChoice == 0 && aiChoice == 2) {
      incWinsElement(wins);
    } else if (playerChoice == 1 && aiChoice == 0) {
      incWinsElement(wins);
    } else if (playerChoice == 2 && aiChoice == 1) {
      incWinsElement(wins);
    }

    incRoundsElement(rounds);

    // For debugging purposes.
    console.log(
      "Player Choice = " + playerChoice + "; AI Choice = " + aiChoice
    );
  }

  /**
   * Updates the the wins element on the scoreboard.
   * 
   * @param {html element} wins 
   */
  function incWinsElement(wins) {
    wins.innerHTML = wins.innerHTML.replace(
      wins.innerHTML,
      "Wins = " + ++numOfWins
    );
  }

  /**
   * Updates the losses element on the scoreboard.
   * 
   * @param {html element} losses 
   */
  function incLossesElement(losses) {
    losses.innerHTML = losses.innerHTML.replace(
      losses.innerHTML,
      "Losses = " + ++numOfLosses
    );
  }

  /**
   * Updates the ties element on the scoreboard.
   * 
   * @param {html element} ties 
   */
  function incTiesElement(ties) {
    ties.innerHTML = ties.innerHTML.replace(
      ties.innerHTML,
      "Ties = " + ++numOfTies
    );
  }

  /**
   * Updates the rounds element on the scoreboard.
   * 
   * @param {html element} rounds 
   */
  function incRoundsElement(rounds) {
    rounds.innerHTML = rounds.innerHTML.replace(
      rounds.innerHTML,
      "Rounds = " + ++numOfRounds
    );
  }

  /**
   * Simulates the ai choosing either rock, paper, or scissors.
   */
  function loadAi() {
    aiChoice = Math.floor(Math.random() * 3);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>A Very Mediocre Rock Paper Scissors</h1>
      <h2 id="header">Select an option...</h2>
      <p id="wins">Wins = 0</p>
      <p id="losses">Losses = 0</p>
      <p id="ties">Ties = 0</p>
      <p id="rounds">Rounds = 0</p>

      <br />

      <button className={styles.button} id="rock" onClick={rockHandler}>
        <Image
          priority
          src="/images/rock_cropped.png"
          width={144}
          height={144}
          alt="rock"
        />
      </button>
      <button className={styles.button} id="paper" onClick={paperHandler}>
        <Image
          priority
          src="/images/paper_cropped.png"
          width={144}
          height={144}
          alt="paper"
        />
      </button>
      <button className={styles.button} id="scissors" onClick={scissorsHandler}>
        <Image
          priority
          src="/images/scissors_cropped.png"
          width={144}
          height={144}
          alt="scissors"
        />
      </button>
    </div>
  );
}
